# Generated by Django 4.1.2 on 2022-10-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='height',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.RemoveField(
            model_name='data',
            name='predictions',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sex',
        ),
        migrations.AddField(
            model_name='data',
            name='song_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
